# Generated by Django 2.1.3 on 2018-12-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='uploaded/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('userprofileinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfileInfo')),
            ],
        ),
    ]
