# Generated by Django 2.1.3 on 2018-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181213_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_name',
            field=models.UUIDField(null=True),
        ),
    ]
