# Generated by Django 2.1.3 on 2018-12-16 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_document_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
