# Generated by Django 2.1.3 on 2018-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181216_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_date',
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.CharField(max_length=255),
        ),
    ]
