# Generated by Django 2.1.3 on 2018-12-16 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20181216_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='userprofileinfo',
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
