# Generated by Django 2.1.3 on 2018-12-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20181216_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='order',
        ),
    ]
