# Generated by Django 2.1.3 on 2018-12-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
