# Generated by Django 2.1.3 on 2018-12-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_document_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_check',
            field=models.BooleanField(default=False),
        ),
    ]
