# Generated by Django 2.1.3 on 2018-12-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_document_upload_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_check',
        ),
    ]
