# Generated by Django 2.1.3 on 2018-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_procces'),
    ]

    operations = [
        migrations.AddField(
            model_name='procces',
            name='document',
            field=models.FileField(default=None, upload_to='proccessed/'),
        ),
    ]
