# Generated by Django 2.1.3 on 2018-12-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_procces_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procces',
            old_name='document',
            new_name='fileUpload',
        ),
    ]
